### ISSUE TITLE
About the DropZone RTS+MOBA

### ISSUE THREAD

**Issue by RafaeLeal** [schuttejoe/schuttejoe.github.io#2]
Hey!

I was quite excited about DropZone when it was in the media, and I even bought the "Pilot Pack" to support the game.
The servers are not up anymore, and there's no news in Steam for years now..

Would you happen to have any plans to get that back online? If not, would you consider open-sourcing it?

Thanks

**Comment by schuttejoe** [comment]
Hey! Dropzone was made by a company called Sparkypants Studios which I no
longer work for or have license for their IP & tech. You can try to reach
out to them but, unfortunately, I can't help you with this.
